### PR TITLE
Add support for disabling signing of emails to unknown addresses

### PR DESCRIPTION
**Pull request by dB-SPL**
The following changes will add the option of disabling signing of emails if the recipient does not have an account on the site.

### CODE REVIEW

**Comment by fabacab** [comment]
Thanks for this patch! I have only glanced at this so far, but it looks pretty good.

The one thing it's certainly still missing is a clean uninstall. Since you've added a setting, you need to add it to [the list of settings to delete upon uninstallation](https://github.com/fabacab/wp-pgp-encrypted-emails/blob/master/uninstall.php#L19), to ensure the plugin can be removed cleanly. Please add that, too, and then I'll run it through my own test site.

Thanks!

**Comment by fabacab** [comment]
Took a closer look at this pull request today and have cherry picked your commits into the current (pre-release) `develop` branch. Although I'm closing this pull request, your commits were cherry picked into the development versions. Please have a look at [the `develop` branch](https://github.com/fabacab/wp-pgp-encrypted-emails/tree/develop) and try out the plugin to make sure my changes are still the changes you'd like to see in the next release. Thanks again for the patch!

**Comment by dB-SPL** [comment]
Thanks.  I'll let you know if I see anything out of place.

**Comment by fabacab** [comment]
@bricehughes Thanks. Let me know either way so that I can move this into the `master` branch if it's working well.

**Comment by dB-SPL** [comment]
I will.  It will probably be Tuesday or Wednesday before I can get it on
our staging server.

Thanks again.

**Comment by dB-SPL** [comment]
I've tried it out with the default PHPMailer and with the [Gmail SMTP plugin](https://wordpress.org/plugins/gmail-smtp/) that some of my sites use.  Both seem to be working the way it's intended.

@rktaiwala Thanks again for your help getting this started.

**Pull request closed without merging**
